# Site settings
title: A blog about Li Haobo
description: A blog about Li Haobo
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Li Haobo
user_description: Hi, this is Li Haobo (李昊波). I'm currently a Ph.D. student at CSE department of HKUST, advised by Prof. Huamin Qu. Befor joining HKUST, I obtained my M.S. degree and B.S. degree from Shanghai Jiao Tong University and South China University of Technology, respectively.
user_title: PhD Student
email: hliem@connect.ust.hk
# twitter_username: lorem_ipsum
github_username:  hobolee
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
